/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tedted29
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();
        refresh();

    }

    ProductClass prod = new ProductClass();
    Connect con = new Connect();

    Object id = null;

    void clear() {
        tfPname.setText(null);
        spinQTY.setValue(0);
        ftPrice.setText(null);
        tfPname.requestFocusInWindow();
    }

    final void search(String keyword) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection(con.url, con.username, con.password);

            String sql = "Select * from tblproducts where id like ? or P_Name  like ?";
            PreparedStatement pstmt = (PreparedStatement) conn.prepareStatement(sql);

            pstmt.setString(1, "%" + keyword + "%");
            pstmt.setString(2, "%" + keyword + "%");

            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel mod = (DefaultTableModel) prodTBL.getModel();
            mod.setRowCount(0);
            while (rs.next()) {
                mod.addRow(new Object[]{rs.getString("id"), rs.getString("P_Name"), rs.getString("Qty"), rs.getString("price")});

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prodDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        tfPname = new javax.swing.JTextField();
        spinQTY = new javax.swing.JSpinner();
        ftPrice = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAddQTY = new javax.swing.JButton();
        xst_qty = new javax.swing.JLabel();
        jaja = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodTBL = new javax.swing.JTable();
        addProd = new javax.swing.JButton();
        updateProd = new javax.swing.JButton();
        deleteProd = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        addProd1 = new javax.swing.JButton();
        updateProd1 = new javax.swing.JButton();

        prodDialog.setLocation(new java.awt.Point(500, 200));
        prodDialog.setMinimumSize(new java.awt.Dimension(321, 300));
        prodDialog.setPreferredSize(new java.awt.Dimension(321, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Insert new product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        spinQTY.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ftPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        ftPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftPriceFocusLost(evt);
            }
        });

        jLabel2.setText("Product Name:");

        jLabel3.setText("Quantity:");

        jLabel4.setText("Price:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAddQTY.setText("Add Quantity");
        btnAddQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQTYActionPerformed(evt);
            }
        });

        xst_qty.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4))
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(tfPname)
                    .addComponent(ftPrice)
                    .addComponent(btnAddQTY, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(xst_qty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(spinQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xst_qty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddQTY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnSave))
        );

        javax.swing.GroupLayout prodDialogLayout = new javax.swing.GroupLayout(prodDialog.getContentPane());
        prodDialog.getContentPane().setLayout(prodDialogLayout);
        prodDialogLayout.setHorizontalGroup(
            prodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        prodDialogLayout.setVerticalGroup(
            prodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jaja.setMinimumSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout jajaLayout = new javax.swing.GroupLayout(jaja.getContentPane());
        jaja.getContentPane().setLayout(jajaLayout);
        jajaLayout.setHorizontalGroup(
            jajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jajaLayout.setVerticalGroup(
            jajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Data Records", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        prodTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Product name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prodTBL);
        if (prodTBL.getColumnModel().getColumnCount() > 0) {
            prodTBL.getColumnModel().getColumn(0).setResizable(false);
            prodTBL.getColumnModel().getColumn(1).setResizable(false);
            prodTBL.getColumnModel().getColumn(2).setResizable(false);
            prodTBL.getColumnModel().getColumn(3).setResizable(false);
        }

        addProd.setText("Add New");
        addProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdActionPerformed(evt);
            }
        });

        updateProd.setText("Edit");
        updateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProdActionPerformed(evt);
            }
        });

        deleteProd.setForeground(new java.awt.Color(153, 0, 0));
        deleteProd.setText("Delete");
        deleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProdActionPerformed(evt);
            }
        });

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        addProd1.setText("search");
        addProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProd1ActionPerformed(evt);
            }
        });

        updateProd1.setText("Add Qty");
        updateProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProd, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(updateProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addProd)
                        .addGap(13, 13, 13)
                        .addComponent(updateProd)
                        .addGap(18, 18, 18)
                        .addComponent(updateProd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(deleteProd)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdActionPerformed
        // TODO add your handling code here:
        prodDialog.setVisible(true);


    }//GEN-LAST:event_addProdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String sPn = tfPname.getText();
        int iqty = (int) spinQTY.getValue();
        Object Opr = ftPrice.getText();

        int x = prod.product(sPn, iqty, Opr);

        if (x == 1) {
            refresh();
            JOptionPane.showMessageDialog(rootPane, "successfully added");

            clear();

        } else {

            JOptionPane.showMessageDialog(rootPane, "you to fill all fields");

        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void deleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProdActionPerformed
        // TODO add your handling code here:
        DELETE_RECORDS();
        refresh();
    }//GEN-LAST:event_deleteProdActionPerformed

    private void updateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProdActionPerformed
        // TODO add your handling code here:

        int table_row = prodTBL.getSelectedRow();
        //this.enableAddProductFields();

        if (table_row != -1) {
            id = prodTBL.getValueAt(table_row, 0);
            Object product_name = prodTBL.getValueAt(table_row, 1);
            Object pro_qty = prodTBL.getValueAt(table_row, 2);
            Object pro_price = prodTBL.getValueAt(table_row, 3);

            tfPname.setText((String) product_name);
            spinQTY.setValue(Integer.valueOf((String) pro_qty));
            ftPrice.setValue(Double.valueOf((String) pro_price));

            prodDialog.setVisible(true);
            //addproductframe.setLocationRelativeTo(rootPane);
            prodDialog.setAlwaysOnTop(true);
            /* save_btn.setVisible(true);
        add_btn.setVisible(false);
        addqty_btn.setVisible(false);*/

            spinQTY.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Select a product", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateProdActionPerformed

    private void ftPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ftPriceFocusLost

    private void addProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProd1ActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        String keyword = tfSearch.getText();
        this.search(keyword);
    }//GEN-LAST:event_tfSearchKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String newpn = tfPname.getText();
        Object newpr = ftPrice.getValue();

        int r = prod.editProduct(id, newpn, newpr);
        if (r == 1) {
            refresh();
            JOptionPane.showMessageDialog(prodDialog, "Product Edit Successfully");
            prodDialog.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(prodDialog, "Problem Editing Produc", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQTYActionPerformed

        String pn = tfPname.getText();
        Object qty = spinQTY.getValue();
        int c = JOptionPane.showConfirmDialog(prodDialog, "Would you like to add\n " + qty + "\n to " + pn + " product?", "Add Quantity", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            int r = (int) prod.addQuantity(id, qty);
            if (r == 1) {
                JOptionPane.showMessageDialog(prodDialog, "Quantity Updated");
                prodDialog.setVisible(false);
                this.refresh();
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_btnAddQTYActionPerformed

    private void updateProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProd1ActionPerformed
        // TODO add your handling code here:
         int row = prodTBL.getSelectedRow();
        if(row != -1){
            prodDialog.setVisible(true);
            prodDialog.setLocationRelativeTo(this);
            prodDialog.setAlwaysOnTop(true);
            btnSave.setVisible(false);
            btnAdd.setVisible(false);
            btnAddQTY.setVisible(true);
            
            id = prodTBL.getValueAt(row, 0);
            Object pn = prodTBL.getValueAt(row, 1);
            Object qty = prodTBL.getValueAt(row, 2);
            Object pr = prodTBL.getValueAt(row, 3);
            
            tfPname.setEnabled(false);
            ftPrice.setEnabled(false);
            spinQTY.setEnabled(true);
            
            tfPname.setText(pn.toString());
            xst_qty.setText(qty.toString());
            ftPrice.setValue(Double.valueOf(pr.toString()));
            spinQTY.setValue(0);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please Select a product", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateProd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProd;
    private javax.swing.JButton addProd1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddQTY;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton deleteProd;
    private javax.swing.JFormattedTextField ftPrice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFrame jaja;
    private javax.swing.JDialog prodDialog;
    private javax.swing.JTable prodTBL;
    private javax.swing.JSpinner spinQTY;
    private javax.swing.JTextField tfPname;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JButton updateProd;
    private javax.swing.JButton updateProd1;
    private javax.swing.JLabel xst_qty;
    // End of variables declaration//GEN-END:variables

    final void refresh() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String conURL = "jdbc:mysql://localhost/enoriadb?"
                    + "user=root&password=";
            java.sql.Connection con = DriverManager.getConnection(conURL);

            java.sql.PreparedStatement pstmt = con.prepareStatement("SELECT * FROM tblproducts ORDER BY id DESC");
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel tblmodel = (DefaultTableModel) prodTBL.getModel();
            tblmodel.setRowCount(0);

            while (rs.next()) {
                tblmodel.addRow(new Object[]{rs.getString("id"),
                    rs.getString("P_name"),
                    rs.getString("Qty"),
                    rs.getString("price")});
            }

            //TFrCode.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProductClass.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void DELETE_RECORDS() {
        int selRow = prodTBL.getSelectedRow();
        if (selRow != -1) {
            int column = 0;
            String id = prodTBL
                    .getValueAt(selRow, column).toString();
            int blabla = JOptionPane.showConfirmDialog(rootPane,
                    "Are you sure you want to delete this Records?",
                    "Delete Confirmation",
                    JOptionPane.YES_NO_OPTION);

            if (blabla == JOptionPane.YES_OPTION) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    String conURL = "jdbc:mysql://localhost/enoriadb?"
                            + "user=root&password=";
                    java.sql.Connection con = DriverManager.getConnection(conURL);
                    PreparedStatement pstmt = con.prepareStatement("DELETE FROM tblproducts WHERE id = ? ");
                    pstmt.setString(1, id);
                    pstmt.executeUpdate();

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ProductClass.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductClass.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else { // meaning if the row is invalid ( -1 )
            JOptionPane.showMessageDialog(rootPane, "Please select a row to be deleted",
                    "No record selected",
                    JOptionPane.WARNING_MESSAGE);
        }       // TODO add your handling code here:
    }

}
